# Settings for LPJmL specifically for coupling (pycoupler)
#   (not covered by LPJmL's direct config)
lpjml_settings:
    country_code_to_name: true
    iso_country_code: true
# Variables to be written to copan_core_data table file 
output:
    farmer:
        - "reasoning"

# Define how copan_core_data table file should be written
output_settings:
    write_lon_lat: true
    file_format: "csv" # "parquet" "csv"

# Define which farmer variables map with coupled LPJmL input variables
coupling_map:
    # fert: ["sdate", "crop_phu"]

control_run: False
